"""task_gistory_table

Revision ID: 0b10cb2f8dc4
Revises: 757f0499b20e
Create Date: 2024-02-12 12:22:29.994646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b10cb2f8dc4'
down_revision: Union[str, None] = '757f0499b20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=False),
    sa.Column('new_assignee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_history')
    # ### end Alembic commands ###
